# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
# Environment Properties
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.1]
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.213
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

## Mod Properties
mod_id=bloom_and_doom
mod_name=Bloom and Doom
mod_license=MIT
mod_version=0.0.19
mod_group_id=com.x29naybla.bloom_and_doom
mod_authors=29Naybla
mod_description=Adapting the universe of the Plants vs. Zombies franchise into Minecraft.

# Required Dependencies
geckolib_version=4.8.3

# Optional Dependencies
jade_version=15.10.4
farmersdelight_version=1.21.1-1.2.9
amendments_version=1.21-2.0.13-neoforge
moonlight_version=1.21-2.29.4-neoforge