modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

updateJSONURL="https://github.com/29Naybla/BloomAndDoom-Neoforge/blob/1.21(.1)/updates.json"

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="bloom_and_doom.png"

credits="PopCap, .vectorwing, Asof, ChiefArug, CodexAdrian, Crispytwig, Lance5057, and Pix3l Spud" #optional

authors="${mod_authors}"

description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
modId="geckolib"
type="required"
versionRange="[4.6.6,)"
ordering="AFTER"
side="BOTH"